### ISSUE TITLE
Message notes cover all other messages again

### ISSUE THREAD

**Issue by alelom** [BHoM/Grasshopper_Toolkit#541] opened 2020-09-17 13:18 UTC
#### Description:

We have again the same behaviour described in https://github.com/BHoM/Grasshopper_Toolkit/issues/480
that was fixed in https://github.com/BHoM/Grasshopper_Toolkit/pull/490.

#### Steps to reproduce:

Have any grasshopper component return a Note and additionally a Warning and/or an Error.
The Note colour will prevail, as described in https://github.com/BHoM/Grasshopper_Toolkit/issues/480.

#### Expected behaviour:

Note should not cover. Same behaviour obtained thanks to https://github.com/BHoM/Grasshopper_Toolkit/pull/490.

**Comment by IsakNaslundBh** [comment] 2020-09-17 15:50
Think this is working as expected on my machine. Using the testmethods produced by you alessio in https://github.com/BHoM/Grasshopper_Toolkit/pull/490#pullrequestreview-377077151

![image](https://user-images.githubusercontent.com/22005920/93495273-3c9cf880-f90e-11ea-81a9-efd7b611c797.png)

**Comment by alelom** [comment] 2020-09-17 15:56
I'm basing this on a specific case I'm having: 
![image](https://user-images.githubusercontent.com/6352844/93495918-8da8ee80-f906-11ea-9f03-affe388f48f3.png)
here the component should turn orange, but it's not.

Before pulling out our hair, I'll do more tests asap.

**Comment by alelom** [comment] 2020-09-17 16:04
Doing this action in `Logging.cs`, as suggested by @IsakNaslundBh:
![image](https://user-images.githubusercontent.com/6352844/93496961-c5646600-f907-11ea-9ac6-1c28ea1bc66b.png)

solved the problem for me.

**Comment by adecler** [comment] 2020-09-18 02:44
> We have again the same behaviour described in #480
that was fixed in #490.

Checking the code on the master, it is exactly the same as it was after the fix in #490. Your own test confirms that the functionality hasn't changed.

@alelom , happy to make the change suggested but first you need to provide a test file that I can easily use to understand why your case is different than all the others. 

@IsakNaslundBh , since you did the initial fix, any insight as to why the if-else is no longer relevant ? I assume it was added for a reason 😄

**Comment by IsakNaslundBh** [comment] 2020-09-18 07:18
> @alelom , happy to make the change suggested but first you need to provide a test file that I can easily use to understand why your case is different than all the others.

My thinking was that @alelom s case reached the logging method multiple times, so some notes had time to get added as remarks instead of blanks, so completely removing the If statement and only adding blanks with solve it.

> @IsakNaslundBh , since you did the initial fix, any insight as to why the if-else is no longer relevant ? I assume it was added for a reason 😄

Forgot the reason yesterday, when I pinged the solution to alessio, but remember again today why it is done in that not so clean way. If a component only contains blank messages, it will not trigger the display of the bubble in the upper right corner, and not  trigger the adding of remarks to the menu... So my suggested solution is no good.

Gah, only thing I can think of then is to check the component for any messages. Clear them and re-add them every time we add events. All for the sake of a faulty enum in GH...

**Comment by adecler** [comment] 2021-02-23 06:16
@alelom , can you provide an example script that reproduces the bug ?

 I have tested this with both the example you provide in https://github.com/BHoM/Grasshopper_Toolkit/pull/490#pullrequestreview-377077151 and the Code Editor and it works as expected.

![image](https://user-images.githubusercontent.com/16853390/108808389-8090d980-75e1-11eb-9ed0-137a34746fc7.png)

**Comment by alelom** [comment] 2021-02-23 09:42
Please find below

https://burohappold.sharepoint.com/:u:/s/BHoM/EaLHWrCr9NVBoz76ubs8DKwBoU2QMt6dd6j4IE8EsbRoug?e=rYww0U


It's the last Execute component on the right.
![image](https://user-images.githubusercontent.com/6352844/108825782-57f5e900-75bb-11eb-96b8-6bf22b35ffc6.png)

**Closed** 2021-02-24 10:42 UTC
Labels: type:bug
