### ISSUE TITLE
Undesired wire created after some call to the global menu

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#475] opened 2020-03-03 10:33 UTC
#### Description:

- when creating a component with ctrl+shift+b, sometimes the input wires are being randomly(?) connected to the existing components

The issue seems to happen quite randomly and we did not find a way to isolate/reproduce it. This does not help (🙈), but it still would be great to get this one resolved in the current milestone as sometimes it gets really annoying and confusing for the end user.

@IsakNaslundBh please feel free to change/supplement this message if I missed something important.

**Comment by adecler** [comment] 2020-03-04 03:56
While the wiki regarding labelling of issues needs to be updated to match the current label set, the guidance it provides still stands. 
> For both of those categories, we have 3 levels of importance:
> - **Critical**: It is simply impossible to continue without either that feature or fixing that bug. No > workaround exists using alternative methods or a quick self-made script. 
> - **Regular**: This is slowing down progress. There is a workaround but it is not exactly ideal. 
> - **Minor**: You noticed a missing feature or a bug but it doesn't stop/slow you in your current work.

This issues doesn't by any mean prevent anyone from working. I would even argue that it barely slow things down since it hasn't happened regularly enough to find a reproducible pattern.

I will add this issue to my list for this sprint but please keep in mind that high priority labels should only be used for issues that need urgent fixing

**Comment by pawelbaran** [comment] 2020-03-05 15:08
@adecler FYI I added one more bug to the list.

**Comment by adecler** [comment] 2020-03-06 01:53
@pawelbaran , it would be much better to raise those as separate issues. Especially given that the PR related for this issue is already ready for review.

**Comment by adecler** [comment] 2020-03-06 02:07
I have now moved the issues to separate ones. This removes the need to solve all of them at once before a PR can be raised and merged.

**Comment by pawelbaran** [comment] 2020-03-06 10:09
Thank you @adecler - my bad I have not done that from the beginning.

**Closed** 2020-03-11 09:06 UTC
Labels: type:bug
