### ISSUE TITLE
Grasshopper_Toolkit: GetProperty returns unconverted BHoM geometries

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#540] opened 2020-09-17 10:35 UTC
#### Description:

The output of `GetProperty` comes out as BHoM geometry, which means that it needs to be explicitly converted before it starts to behave like a native GH/Rhino geometry:

![image](https://user-images.githubusercontent.com/26874773/93459415-f6ca3b00-f8e1-11ea-9e0f-53e2c033e7f4.png)

It is a quite annoying issue, particularly to the non-expert users.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGrasshopper%5FToolkit%2FGrasshopper%5FToolkit%2DIssue540%2DGetPropertyCast&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

**Comment by adecler** [comment] 2020-09-18 03:59
Ok, I haven't touched that part of the code in a very long time so I am a bit rusty in the specifics of GH. @epignatelli , feel free to jump in if I am missing the obvious. In the meantime, I will document what  I find here.

Any Grasshopper Param (including the BHoM parameters we created) has two casting methods:
- `CastFrom(object source)` :  this is called when the parameter is reading its input value (i.e. when the component that own the parameter is being run).
- `CastTo<Q>(ref Q target)` this is called when the parameter is being asked to provide it value to another parameter (i.e. when the param is plugged into the input of another component and that component is executed).

This is a great feature from GH because it means we don't have to constantly convert back and forth between BHoM and Grasshopper when we are chaining BHoM components (we can just stay in the BHoM realm). So big improvement in efficiency an reduction of risk of errors due to casting (e.g. nurbs curves)

Here's  where the problem lies in this case: for some reason the GH Area component is not asking the PlanarSurface output param to cast its content. As we can see, it works fine for things like the GH component that calculate the distance between points.

![image](https://user-images.githubusercontent.com/16853390/93553300-3c037100-f9a5-11ea-97a3-3e0e8a80a61f.png)

Since the input of the `Area` component is a `Geometry` param, I have tried this:

![image](https://user-images.githubusercontent.com/16853390/93553470-a3b9bc00-f9a5-11ea-8ed6-72a1ae04a54e.png)

And, to no big surprise, the `Geometry` param is the culprit as it does not casting 😢 

This is where I am a bit unsure what to do and you might have some idea @epignatelli . We obviously want to keep the feature that BHoM geometries are only casted when needed and we cannot modify the geometry param ourselves. Detecting that the next param of our output is a GH geometry is no good either since we can have multiple outputs.

**Comment by adecler** [comment] 2020-09-18 06:29
Closing as replaced by #543

This will be be fixed next quarter as it requires breaking changes. Since it has been there for quite a long time, I think we can afford a  few more weeks 😉

**Closed by adecler** 2020-09-18 06:29 UTC
Labels: type:bug

**Comment by epignatelli** [comment] 2020-09-18 08:52
This experience keeps popping up, but I am afraid there is little we can do.


The `G` parameter of the `Area` component receives the `GH_IBHoMGeometry` from the `GetProperty` component correctly, and calls the `SolveInstance` method. There is no actual exception raised in the grasshopper component.
It's just that its `SolveInstance` method doesn't handle the input in a way that requests a cast. It just assumes there is something to work with, if it doesn't find it, it logs a message saying "I can't do it!".

Example of methods that handle it correctly in grasshopper are `Move` and `Scale`, to demonstrate the problem is localised in the `Area` method:
![image](https://user-images.githubusercontent.com/26899347/93577466-ff7b4980-f993-11ea-8b2a-712b4b51809b.png)


I am afraid we can't do much about it. The casting mechanism works correctly in my opinion.
I'd suggest keeping this issue open and reference the solution of manually casting with a grasshopper parameter to avoid people forgetting and reopening in 6 months.

**Comment by pawelbaran** [comment] 2020-09-18 09:19
Looks like I was really lucky with my first shot @epignatelli 🤣 I randomly picked `Area` with no actual thought behind the choice. I just remembered that there is at least a few components that keep on breaking and annoying the user now and then - possibly all of them are simply buggy. If so, would it be worth dedicating a separate Wiki page to that issue, at least until we find a solution? @al-fisher @IsakNaslundBh @adecler

**Comment by epignatelli** [comment] 2020-09-19 12:03
Yeah, I there might be a few that would not work (I don't remember the others honestly). 
I think the point is that the code is not buggy form the Grasshopper perspective.
I guess they don't expect to receive a geometry object that is not valid, but could be just by requesting a cast.

I think it is buggy from our perspective though :)
