### ISSUE TITLE
Stop nodes from executing for empty branches

### ISSUE THREAD

**Issue by arturtomczak** [BHoM/Grasshopper_Toolkit#555] opened 2020-10-09 09:36 UTC
#### Description:
Unlike most Gh nodes, BHOM methods raise red error when supplied with data structure containing empty branches. Empty branches are sometimes desired to avoid excessive tree operations. Would be good if BHOM could simply ignore those branches and work properly for the rest of items.

#### Steps to reproduce:
Supply for example Node method with a data structure containing empty branches. See attached example.

#### Test file(s):
[Empty branches test script.zip](https://github.com/BHoM/Grasshopper_Toolkit/files/5353920/Empty.branches.test.script.zip)

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/34334902/95567388-2b35a080-0a23-11eb-96d4-14d5393db5e9.png)

**Comment by adecler** [comment] 2021-02-23 10:20
Empty branches are being executed because Grasshopper doesn't make a distinction between no data and null data. This means that solving this would also prevent BHoM components to accept null as a valid input. Here's a similar script to yours that would leverage Grasshopper detection of empty input:

![image](https://user-images.githubusercontent.com/16853390/108827262-5c90c080-7600-11eb-81e2-2d837e1846b6.png)

As you can see, null inputs would also prevent the execution of the component. As null inputs is something supported by the BHoM framework, we cannot fix this issue while keeping the same level of functionality in the BHoM. It is technically possible to override some of the Grasshopper code but this is something that should only be done in extreme cases as it makes the BHoM compatibility with Grasshopper very fragile.

To better understand the impact of not solving this issue, here's the two problems currently caused by empty branches on the BHoM:

- If the method called by the component doesn't run the necessary null checks, empty branches will result in the following error message: `Object reference not set to an instance of an object`.
- The component is executed on empty branches which might result in a loss of performances. 

From a discussion with @al-fisher , @IsakNaslundBh , @FraserGreenroyd , @alelom , @rolyhudson , and @AndreBalasian we agreed that

- All methods missing null checks should be fixed. Additional tests should be included to our test framework to guarantee that all methods can handle nulls correctly. This will fix the problem of having error messages on empty branches. Issue raised here: https://github.com/BHoM/BHoM_Engine/issues/2335
- The lost of performance is something that can be handled by the user through tree manipulation. We therefore agreed that it was acceptable to not resolve this issue.

**Closed by adecler** 2021-02-23 10:20 UTC
Labels: type:bug
