### ISSUE TITLE
Grasshopper_Toolkit: Different types for explode failing

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#342] opened 2019-04-03 09:55 UTC
The explode in the new UI fails for custom objects if the type defined varies. This worked before in the old 2.0 UI. Is there something we can do to make this function again?

I know that it is possible to specify the type in the CreateCustom in Grasshopper, but if the objects is coming from somewhere else, like Excel or similar, you might not have that capability.

![image](https://user-images.githubusercontent.com/22005920/55470034-18a90280-5607-11e9-9cfa-a1803a57f891.png)

File saved here:

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Grasshopper_Toolkit-Issue341-ExplodeCustomVaryingProeprtyType?csf=1&e=duGdSZ

**Comment by epignatelli** [comment] 2019-04-26 09:42
Duplicate of https://github.com/BHoM/BHoM_UI/issues/72.

Is it correct? If so, is it ok to close this?

**Closed** 2019-06-10 10:21 UTC
Labels: priority:low, severity:critical, type:bug
